name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache cargo registry, git, and target
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ hashFiles('Cargo.lock') }}

      - name: Install trunk
        if: steps.cache-cargo.outputs.cache-hit != 'true'
        run: cargo install trunk

      - name: Trunk build
        run: trunk build
